name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0' # Ou a versão do Node.js que você preferir

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
        # Opcional: Se você deseja rodar o linter como parte do processo de CI

      - name: Build Project
        run: npm run build
        # Certifique-se de que isso gera os arquivos estáticos no diretório correto (ex: 'dist')

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4 # Certifique-se de usar a versão 'v4' ou mais recente
        with:
          name: github-pages # Este é o nome do artefato que será usado no deploy
          path: dist/ # Ou o caminho para o diretório onde os arquivos de build são gerados

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # Não é necessário especificar 'id: deployment' a menos que você precise referenciar esta etapa especificamente mais tarde
