name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0' # Use a versão específica do Node.js que você está usando localmente

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
        # Opcional: Se você deseja rodar o linter como parte do processo de CI

      - name: Build Project
        run: npm run build
        # Este passo é crucial para capturar erros de compilação

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # O deploy agora só acontece se os passos anteriores forem bem-sucedidos
